### ISSUE TITLE
Package as .app/.exe/.deb

### ISSUE THREAD

**Issue by cafca** [cafca/souma#1]

**Comment by cafca** [comment]
Dependent on https://github.com/ciex/soma/issues/20

**Comment by cafca** [comment]
https://github.com/cloudmatrix/esky/

**Comment by cafca** [comment]
Packages for OS X can now be made with `python setup_osx.py py2app`.
Distribution through the Python Package Index also works, Souma can be installed with `pip install Souma`

**Comment by cafca** [comment]
https://github.com/ciex/souma/pull/117 implements packaging for osx

**Comment by Trami** [comment]
ist das Ticket #1? :)

**Comment by cafca** [comment]
Was? :D Ja

**Comment by cartisan** [comment]
Bis auf .deb done. und Unixer kennen sich ja eh mit Konsolen aus. :D
