### ISSUE TITLE
Create IK poster

### ISSUE THREAD

**Issue by cafca** [cafca/souma#127]
![2014-02-19 16 33 28](https://f.cloud.github.com/assets/278463/2208083/ac9f7a62-997b-11e3-9504-d4b8c1a35467.jpg)

**Comment by cafca** [comment]
`Collection` is a gradient from coordinating groups > communication > personal development
- Group self-organisation (decision making, action planning, knowledge representation)
- Group formation through interest model
- Conversation architecture
- Starmaps
- Self-determined filter bubble
- Identity & Self (-observation, -determination, -development)

**Comment by Trami** [comment]
here's the prezi in which you can put your stuff :) hope you all can edit...
http://prezi.com/7ttrp93g0d4b/?utm_campaign=share&utm_medium=copy

(zoom out and move the canvas to the right)

**Comment by cartisan** [comment]
preliminary poster here: http://prezi.com/7ttrp93g0d4b/souma-identity-and-development-ik/

**Comment by Trami** [comment]
protocol: meeting on March, 10th 2014

## one minute pitch
- postponed to Wed, around 2.30pm

## poster production
- use inDesign
- print A0 poster
- discussion: what makes Souma distinct from other social media?
  - open source
  - encryption
  - emphasises the social dimension of human life
  - self-determination: control over where my data goes
  - self-development: transparent filter bubble

## transport
- buy tickets
- bus info to IK people

## open questions
- logo design by Joh Schleith? 
- agenda topic for student body: financial support

## action items
- contact: @johsh (logo) –> Trami
- write to Joe (money) –> Trami
- write to christine harms (bus) –> Leon, Slawa
- meeting tomorrow

**Comment by wloev** [comment]
11.03.2014

## Pending action items
- Proof read poster content, scan for triviality @ciex 
- Write the technical part of poster, supplement with pictures @ciex 
- Layout poster in InDesign @ciex @cartisan 
- Print poster (as cheap as possible) @all
- Prepare 1-minute pitch @Trami 
- Bring along your swimming things, table tennis stuff and booze @all @ciex

**Comment by cafca** [comment]
I wrote this re: technical details. Not sure about the required level of detail.

### Draft: Tech Details

The Souma client is implemented as a modular system whose components share a signaling namespace and a database. The main modules are handling presentation (Web UI), synchronisation (Synapse) and analytics (Astrolab). All Souma client installations also have access to a central web service (Glia) that handles identity management and (centralised) data exchange (Myelin).

The presentation layer is implemented as a locally running web server using the Python programming language and the Flask framework. The user uses this service by pointing their browser at a URL that is only accessible on their own computer. Here they have access to all content that was posted by their network or themselves. It is displayed in a non-scrolling magazine-like paged layout. Through these design choices we try and achieve an organisation of information around topics instead of data sources. We want to engage content creators as well as curators and thus develop not only tools for posting contents, but also for restructuring and curating them.

In order to filter content, an LDA topic model based on the English-language Wikipedia is distributed along the client and used to assign topics to every posting. Combining this data with indicators of interest/disinterest from the user allows us to model the user's interest and apply this model to all new contents. Our aim in this is to increase relevance for the user while keeping her at control of the process by allowing direct manipulation of the interest model. For this we will visualise the interest model as part of the user interface and allow its direct manipulation. Thereby we allow the user to develop self-determination with respect to which contents get her attention and which information sources are allowed to influence her.

Data submitted by the user is end-to-end encrypted in the Synapse component using the Google Keyczar libary and distributed using the proprietary Vesicle data format. Data transport is facilitated through a central server (Glia server) also programmed using the Flask framework. The Vesicle protocol is designed to allow for a later transition to a completely decentralised network architecture using the BitTorrent and DHCP protocols. To reduce bandwidth and hard drive utilisation it can use convergent encryption to encrypt contents in this case.
