### ISSUE TITLE
Get feedback on Discussion Architecture text for the IK

### ISSUE THREAD

**Issue by wloev** [cafca/souma#131]
Please comment on: https://github.com/ciex/souma/wiki/Discussion-architecture

Is it comprehensible? Do you get an idea of what it is and how it works? Is it too long/short? Which points aren't clear, which redundant?

**Comment by Trami** [comment]
paper on brainstorming technology for group decision-making... maybe contains some relevant features of how to design CA as to form a backdrop for decision-making.
(you can access it from the uos network)
http://delivery.acm.org/10.1145/640000/637073/p16-applegate.pdf?ip=131.173.191.18&id=637073&acc=ACTIVE%20SERVICE&key=2BA2C432AB83DA15%2E2BB856C4FB99BD06%2E4D4702B0C3E38B35%2E4D4702B0C3E38B35&CFID=298585844&CFTOKEN=70185133&__acm__=1394018223_43ff4d83b876ea340e3b81d6434d6813

**Comment by Trami** [comment]
p.s. will comment on the page tomorrow :-)

**Comment by Trami** [comment]
I put the feedback here and below the wiki entry:
https://www.dropbox.com/s/9pnhxbxo53tzmgu/feedback%20on%20CA%20wiki%20entry.pdf

**Comment by Trami** [comment]
feedback is there :-)

doodle participation nicht ;-)
