### ISSUE TITLE
Create comments UI

### ISSUE THREAD

**Issue by cafca** [cafca/souma#14]
- add comment
- display comments in popover
- delete comment
- reply to comment

**Comment by cartisan** [comment]
Implemented adding and displaying comments (397e0e914ee627b2abf062c30e631830aea4774b). 
No restriction on number of comments to be displayed for each post, as of now. Thus also no popover. Replying to comments is possible in theory but I haven't enabled it now to keep things simple design-wise.

**Comment by cafca** [comment]
Closed by #149
