### ISSUE TITLE
Identify Link in text

### ISSUE THREAD

**Issue by cartisan** [cafca/souma#142]
Instead of posting the link in an extra field we want to extract all the links from the text-planet or text-attribute of a star. Thus we have Facebook-Like behaviour and can post multiple links at the same time.

@ciex

**Comment by cafca** [comment]
We don't even have to do it in JS. We can just reduce the _post star_ interface to a single text box and parse all links using regex in Python. Then we retrieve headers for all URLs to see whether they are Images or Documents and create appropriate Planet objects for the Star.

**Comment by cafca** [comment]
I can give it a try tomorrow.

**Comment by cartisan** [comment]
Now that you say so: ...sounds quite plausible!
