### ISSUE TITLE
Schema migration

### ISSUE THREAD

**Issue by cafca** [cafca/souma#162]
@cartisan @kahartma 

How can we handle changing schemas? We will have to deal with schema changes from version to version. The user's database should be updated along with the code. Is there a "good way" to do this?

**Comment by cafca** [comment]
Found [this](https://alembic.readthedocs.org/en/latest/)

**Comment by cartisan** [comment]
Sounds reasonable to me, didn't find any negativity about it on the interweb. Found an integration for alembic to flask though: http://blog.miguelgrinberg.com/post/flask-migrate-alembic-database-migration-wrapper-for-flask
