### ISSUE TITLE
Implement polling / regular client updates from myelin

### ISSUE THREAD

**Issue by mrausch** [cafca/souma#25]
TODO
- Periodically send starmap_requests (see also request_inventory in synapse)
- Spawn function every 3 minutes (see gevent's spawn_later)
- Problem: We need UDP Hole Punching in order for starmaps to be delivered from the operator back to the client

**Comment by cafca** [comment]
Solved by transition to server-based communication in 87a2ec7692038bac93a2f88a842e7810f122a557
