### ISSUE TITLE
Document current UI design philosophy

### ISSUE THREAD

**Issue by mrausch** [cafca/souma#33]
In this semester, I would like focus on the user interface of the application. The current interface as designed by Vincent has a nice aesthetic in my opinion, but there is no real documentation yet as to why certain UI design decisions have been made.
In order to start a "UI research" branch in the study project, I would like to start off by describing the current UI design and interview Vincent about certain design decisions that he has made when implementing the UI. The gathered information shall be documented on a dedicated wiki page, as a basis for
- other people in the project that want to work on the UI design
- discussion about possible UI design refinements
- further UI design documentation (e.g. magazine layout)

**Comment by cafca** [comment]
Wiki page: https://github.com/ciex/souma/wiki/User-interface-design

**Comment by cafca** [comment]
List of views, on the left are content-based views, on the right are meta views for settings, etc.

Red dot = drafted

![snapshot-d3f19d17-a1ef-41d4-906c-edb03896dd8f](https://f.cloud.github.com/assets/278463/1632836/56241f1a-577e-11e3-8a39-9720b07ab708.jpg)

**Comment by mrausch** [comment]
Some design sketch for discussion:
![design_sketch_2_mrausch](https://f.cloud.github.com/assets/473925/1654679/447e169e-5b52-11e3-99d3-2f890cbf7f21.jpg)

**Comment by cafca** [comment]
menu in the upper left reminds me of http://sparanoid.com/lab/path-menu/#

**Comment by Trami** [comment]
find die Anordnung der Elemente sehr hübsch. v.a. das Menü gefällt mir: übersichtlich, spart Platz, ist schön

**Comment by Trami** [comment]
da fehlt übrigens der reflection Teil
