### ISSUE TITLE
Write up an overview of the project organisation (who is working on what, when)

### ISSUE THREAD

**Issue by cafca** [cafca/souma#49]
We will start to make an overview of the topics which are of our knowledge. The output should be a document which then has to be complemented with information from all members in order to specify the various topics and to add new fields of research as work develops.

Assigned: @Trami @mrausch

**Comment by Trami** [comment]
@mrausch do you want to meet tomorrow or on Monday?

**Comment by mrausch** [comment]
Not in Osna tomorrow, so Monday please :)

**Comment by Trami** [comment]
time and place? i’m flexible tomorrow.. :)

**Comment by mrausch** [comment]
Sorry for late reply. Can we maybe postpone this until tomorrow? I'm available all day tomorrow after our meeting.

**Comment by cafca** [comment]
How is this coming along? You could create a Wiki page listing project members and then we can start describing their tasks.

**Comment by cafca** [comment]
Missing now are
@AtikJam @kahartma @Scolor 

Please add a summary of what you have done to https://github.com/ciex/souma/wiki/Team!
