### ISSUE TITLE
Present Souma at HIT

### ISSUE THREAD

**Issue by cartisan** [cafca/souma#60]
Study Projects will be presented at Hochschulinformationstag (21.11), 12 pm, at Building 1.
@Trami and @AtikJam will talk on our behalf. The expectations are 15 min talk and 5 min discussion.

Subtask:
- Meet and plan the talk

**Comment by Trami** [comment]
you can now find the presi here:
http://prezi.com/xpnqgsd3elhh/?utm_campaign=share&utm_medium=copy

we collected a list of around 25 mail addresses of pupils interested in beta-testing
