### ISSUE TITLE
Create a wiki wrap up of group-self talk 

### ISSUE THREAD

**Issue by cartisan** [cafca/souma#61]
We didn't have time to discuss @wloev and @AtikJam talk on group self and collaboration. We need to find a way to do this using the wiki.

Subtask:
- get information into wiki
- fuel discussions on subtopics

**Comment by cafca** [comment]
Video visualizing submissions to the Git software, which reminded me of what you said about profiles:
http://www.youtube.com/watch?v=GTMC3g2Xy8c

Paul Adam' presentation of "The real life social network"
http://www.slideshare.net/padday/the-real-life-social-network-v2

**Comment by cartisan** [comment]
Social network that uses gamification and elevate social pressure to induce motivation:
https://www.fitocracy.com/

(Could also be interesting for @hmerkel)

**Comment by cafca** [comment]
"elevate social pressure to induce motivation" :suspect:
