### ISSUE TITLE
Schedule and conduct meeting for the IK 2014

### ISSUE THREAD

**Issue by mrausch** [cafca/souma#68]
- [x] Create a doodle and find a meeting date
- [x] Discuss what we could present at the IK 2014 using a poster

**Comment by cafca** [comment]
@cartisan @Francois23 @Trami We will meet Monday at 12 ct in the study project room in building 69, first floor, take the corridor to the left, last door on the left.

**Comment by mrausch** [comment]
I will not be able to attend the meeting physically. Can somebody run Skype on his Laptop so I can attend the meeting remotely? That would be great!

**Comment by mrausch** [comment]
Link to poster guidelines: http://www.interdisciplinary-college.de/index.php?id=1822

DIrect link to PDF: http://www.interdisciplinary-college.de/fileadmin/user_upload/IK-2011/Poster_Abstract_Template_IK_2014.pdf

**Comment by cafca** [comment]
![img_20131202_133801](https://f.cloud.github.com/assets/278463/1654532/b0a63d1e-5b4e-11e3-805c-c3d0f83d0b56.jpg)

**Comment by Trami** [comment]
schedule a second meeting @wloev
