### ISSUE TITLE
Extend PageManager for more complex Layouts

### ISSUE THREAD

**Issue by cafca** [cafca/souma#69]
Given a list of objects, select a layout that maximizes how much the user is interested in the page
- [x] PageManager should take a list of objects instead of a list of Stars
-  ~~Layout cells can have children~~
- [x] Layout cells have a restrictions attribute that determines the media kinds that can be displayed in this cell
- [x] Layouts have a key:list for every kind of content that is included in the layout (stars, create_star form, etc.)

**Comment by cartisan** [comment]
PageManager is now a full-fledge class with methods for creation of every kind of page with content that needs layering. It produces a page that again a class in its own right. The layout.js contains key-lists for every kind of content that is intended to be in the layout. Do we still need child-cells with our current approach and state?

**Comment by cafca** [comment]
I think we can leave that for later, and another issue.
