### ISSUE TITLE
Second meeting for IK 2014

### ISSUE THREAD

**Issue by wloev** [cafca/souma#73]
- Find new time which fits all interested people.
  Doodle poll: http://www.doodle.com/fsm5pysmdvakz239
- Do meeting

**Comment by cafca** [comment]
Meeting on Fri 6 Dec
14:30 - 16:00
Attendance: @Trami , @ciex, @AtikJam , @cartisan , @hmerkel  and @wloev 
Protocol: Vincent
- Recap of monday's meeting #68 
- Leon presents a model of our motivation
- We map components of our implementation to the motivation model to see where we need to extend it
- Trami will create a wiki page of the results  (see #75) and present it at next Tuesday meeting
- Idea: Weekly Tuesday meetings should have a moderator in addition to a meeting secretary who 1) tries and keeps the discussion from becoming off topic and 2) who keeps a record of the discussion on the black board
- Idea: Discussion could become better if we have a devil's advocate who tries to recklessly criticize group think (?)
- Slawa and Atik will give a short recap presentation of their implementation ideas at the next Tuesday meeting

![imag0344](https://f.cloud.github.com/assets/278463/1693157/b2daf5aa-5e89-11e3-848e-3023613a8658.jpg)

**Comment by Allesa** [comment]
Hey guys,

I could take the role of the moderator and the devil's advocate sounds something that could fit me too :)

**Comment by wloev** [comment]
In principle the moderative roles should be assigned randomly for the reason that the role and not the one who is acting it out is to be held responsible for the negative feedback (critizing positions, stifle regressive discussions) that goes hand in hand with such a role. It should not become a personal matter. However, guess someone has to start, so great that you volunteer, Allesa. Though the devil's advocate AND the moderator in one person sounds like an amassment of power qua roles and we all know what history has to say on this  ;) So better pick one role.

**Comment by Allesa** [comment]
:D Ok, got it. 
Guess we'll decide about it on the spot already.

P.S. 
http://i.imgur.com/x2LQjbq.gif
