### ISSUE TITLE
Create wiki page summarizing results from IK meeting

### ISSUE THREAD

**Issue by cafca** [cafca/souma#75]
See #73 for an image of the meeting board

**Comment by Trami** [comment]
@cartisan: I've started to sketch the model you and Vincent were developing. Not sure I got exactly what you meant. Rather I'm pretty sure it's my interpretation of what we could make out of it.. :) Can you read and edit?

**Comment by cartisan** [comment]
@Trami: Link to the sketch? If you mean the whiteboard picture we took after the session then I'm completely d'accord!

**Comment by cafca** [comment]
Found it https://github.com/ciex/souma/wiki/Our-philosophy

**Comment by cafca** [comment]
Some thoughts I had about the summary of our values:

```
* be open source
```

Is that limited to making our source code freely available? I would go further than that, I would want our software to not only be open source, but also be hackable, redistributable, modifiable. That would be [free software](http://www.gnu.org/philosophy/free-sw.html), wouldn't it?

```
* be non-commercial (not primarily commercial)
```

What does non-commercial mean? I feel that we haven't found our middle ground here yet. We need to be able to pay for servers, eventually pay for programmers if we continue with the project in the next year. How is that compatible with being non-commercial? We don't want to subordinate our original goals to the rules of a corporate mindset, that's for sure. But how do we get there?

```
* support the development of users in groups
```

Isn't it more that we want to support self-development in general? Be it in groups or not. But yes.

```
* support secure and free communication
```

Secure and free _from what_? We want to be secure from institutional surveillance but we also want to be secure from fraud and criminals. We want to be free from excessive social norms but we also want to be free from stumbling over disgusting gore pictures of rotten corpses. Is that self-determined communication?

**Comment by cartisan** [comment]
Agree in 1 & 3. But if we want to be free from social norms and provide tools that do not imply norms on their users we'll have to accept some groups' interest in, alas, rotten corpses. All we need to do is comply with the legal code. Reddit ist doing a good job on this.

**Comment by cafca** [comment]
You are right of course. What I meant was that I, personally want to be free from having to look at rotten corpses which means that there needs to be a mechanism to filter information to meet my personal norms.

**Comment by cafca** [comment]
https://github.com/ciex/souma/wiki/Our-philosophy
